### ISSUE TITLE
Tackle YouTube Ads

### ISSUE THREAD

**Issue by chanpreet1999** [chanpreet1999/YoutubeAutomator#3]
any way to bypass the YoutTube ads or skip the ads by clicking the `Skip Ad` Button

**Comment by chanpreet1999** [comment]
Use default add blocking browsers that run on the same engine as chromium Ex Brave browser blocks ads automatically.

**Comment by chanpreet1999** [comment]
added support for brave browser

**Comment by baljinderxd** [comment]
> added support for brave browser

is it possible to extend support for opera browser? xD
