### ISSUE TITLE
Limit the amount of tabs 

### ISSUE THREAD

**Issue by chanpreet1999** [chanpreet1999/YoutubeAutomator#5]
Limit the  amount of tabs opening in parallel mode

It is possible that a playlist  consist  of 100+ vids in such a scenario **100+ tabs will be opened parallely** and will try to take SS of videos, which is **Highly RAM Consuming.**

Limit the  amount of tabs opening to 10.

**Comment by chanpreet1999** [comment]
Updated the code, now videos will open in a set of 5 while using parallel playlist.

**Comment by baljinderxd** [comment]
> Updated the code, now videos will open in a set of 5 while using parallel playlist.

Can this value of 5 be changed in code according to our need? Slow internet issues :)

**Comment by chanpreet1999** [comment]
yeah sure
would you like an update where the number of tabs is also taken as input from the user

**Comment by chanpreet1999** [comment]
I thought of implementing it, but then the commands will also become longer

**Comment by baljinderxd** [comment]
Nah, just information about where to edit the code for this will be enough i guess🤓

**Comment by chanpreet1999** [comment]
Line 182 and 183 that's it
````
            arrToWrite = await limitParallel(browser, href, idx, idx + 5, arrToWrite);
            idx = idx + 5;
````
change these lines and you'll be good to go

**Comment by baljinderxd** [comment]
> Line 182 and 183 that's it

thanks 🤓
